### ISSUE TITLE
Debian 7.7

### ISSUE THREAD

**Issue by Likeyn** [boxcutter/debian#20]
Hey, first thanks for maintaining these repos, they proved useful quite a few times to me already!

I noticed Debian's 7.7 version has gone missing from your Atlas account (and from this repo after a quick check), any chance you could bring it back? I've got some Debian 7.7 servers running atm and not planning to upgrade'em to 7.9 just yet... Of course I could just host a Debian 7.7 box by myself for my special needs but I thought it'd just feel great to have everything centralised in boxcutter repos?

Lemme know what you think :)
Thanks

**Comment by annawake** [comment]
I've added back some of the old versions, but I'm having difficulty getting 7.7 to build on the new box-building toolchain (vagrant 1.7.4, packer 0.8.6, virtualbox 5.0.6/vmware 8) - it hangs on ssh.

If you want to sort out this issue and submit a PR to fix, I don't mind building it.  But I'm not going to spend any additional time trying to troubleshoot getting the old releases working, since the newer 7.x ones don't have these issues.

**Comment by Likeyn** [comment]
Understood, makes sense. I'll give it a shot if I ever get a chance :) Thanks for adding back 7.8 (and 8.0 and 8.1) anyway!
