### ISSUE TITLE
debian82 gone, debian85 now?

### ISSUE THREAD

**Issue by ShelterJames** [boxcutter/debian#37]
Firstly, thanks for providing this service and sorry if this isn't the right place to raise this but I couldn't find another contact point.

debian82 box seems to have gone? I'm guessing this is because there is now a debian85 box instead?

Is the removal of debian82 a deliberate policy to force people on to the latest version? Was there any cross over period when debian82 and debian85 were available during which people should have upgraded? Is there an email list or push notification service that would have told users this?

It's just that anyone now trying to use my vagrant scripts for the first time will get 404 errors. They only work for me locally because I have debian82 cached. 

I would be interested in:
-  a policy of leaving debian82 in place for existing users. However I understand you may be wary about supplying out of date software, and I don't want to demand more work. 
-  could there be an announce only email list (Google Groups for a free service) so users can be aware of changes as they happen?
-  could there be a debian8 box that will always be the latest version of debian8? Then those that don't care about minor differences can just run this and not have to worry about renaming debian82 to debian85.

But, again, thanks for the service!

**Comment by annawake** [comment]
It's not us but rather the debian project themselves - it is very difficult to find mirrors that keep installation media older than the last point release or two. The project removes direct HTTP/FTP downloads quickly and people trying to make boxes from these templates often discover that the link to the install ISO is broken. (People would constantly get 404 errors trying to build our boxes).

An important goal of these templates is that it is supposed to be easy to update the boxes and build them on your own.

I don't have the time to create/maintain a quality email list, and if it can't be done right, it's not worth asking for your attention.

It's the first time someone has asked for "stable" box alias names. I'm not against the idea, particularly because debian seems to make point releases so frequently compared to the other distributions. I can't always say that we will keep up with the latest version of debian8 - for example we skipped two point releases of debian, partly because for awhile the tools weren't keeping up so that they could be built easily and partly because I didn't have the extra time to fuss with it given my other committments. But it is possible to say that it will have the last one we built for consumption.

How do you think we should avoid confusion with the existing nomenclature? Should that be ended (having debian85, debian84, etc.) and just have a `debian8`?

**Comment by ShelterJames** [comment]
> a quality email list, 

I'm not expecting any great works of writing, don't worry :-) But even quick notices "debian82 removed, please switch to debian85" or "new box ubuntu1610 is now the release version not dev channel" would be useful - at the moment, is there any way to get this information apart from constantly checking the webpage?

> and if it can't be done right, it's not worth asking for your attention.

(On a personal note: Hah, some of my tech projects have been run in the exact opposite way!)

> I can't always say that we will keep up with the latest version of debian8 - for example we skipped two point releases of debian

Personally I'm not bothered by that - ppl can always run apt-get in the bootstrap scripts if that is really an issue ....

> How do you think we should avoid confusion with the existing nomenclature? Should that be ended (having debian85, debian84, etc.) and just have a debian8?

Well, in the long run, I personally would be happy with having just "debian8", "debian9", etc. But I wonder if some people would prefer stability from builds and would want to have "debian82" and "debian85"? Difficult. I guess having both would be nice, with "debian8" just exactly the same as whatever the latest "debianX" is, but I haven't published boxes on Atlas so I have no idea if that would be a small build script tweak or a real pain :-)

(In the short run, now "debian85" is up ppl might be using that, so best to keep?)

And also, to be a pedantic ass, I would change "debian85" to "debian8-5" or something in future releases. It will just offer extra clarity by the time we get to "debian101" :-)

So .... not sure basically! Sorry. But again, thanks for your work on this.

**Comment by annawake** [comment]
The closest thing we have to that are the release notes in the CHANGELOG.md - so sorry that it wasn't noted in there, I'll try to make sure things like this don't get overlooked there in the future.

Since Debian releases point releases so frequently and the debian project doesn't host old install ISOs for very long, we'll switch to `debian8` and `debian7` respectively in the next release of the VMs.  This will be a slightly different convention from the rest of the boxcutter builds, but perhaps makes more sense given both of the former.

We're effectively doing that now, just assigning a new label every time.  Makes sense to make the label the same. Thus I see no point in having two different conventions. An important component to this template archive is that people can grab the source, build and customize these templates themselves - with Debian we have constant issues with the links to old install ISOs being invalid. With Debian it makes the most sense to just embrace the new.

**Comment by ShelterJames** [comment]
Ok. It sounds good to me anyway. :-)

Thanks for looking at this and your work on this project.
